version: "3.9"

services:
  front-end:
    container_name: vue-frontend
    build:
      context: ./view
    ports:
        - "80:80"

  weather:
    container_name: weather-service
    build:
      context: ./weather
      dockerfile: ./src/main/docker/Dockerfile.multistage
    ports:
      - "9080:8080"

  tour:
    container_name: tour-service
    build:
      context: ./tour
      dockerfile: ./src/main/docker/Dockerfile.multistage
    ports:
      - "8086:8080"

  place:
    container_name: place-service
    build:
      context: ./place
      dockerfile: ./src/main/docker/Dockerfile.jvm
    ports:
      - "8080:8080"
