---
openapi: 3.0.3
info:
  title: Generated API
  version: "1.0"
paths:
  /place/getPlaces/{city}&{radius}:
    get:
      parameters:
      - name: city
        in: path
        required: true
        schema:
          type: string
      - name: radius
        in: path
        required: true
        schema:
          format: double
          type: number
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Place'
  /place/version:
    get:
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:
    Place:
      type: object
      properties:
        address:
          type: string
        category:
          type: string
        id:
          type: string
        name:
          type: string
